server:
  port: 8086
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/book-service/**
        - id: book-rematch
          uri: lb://book-rematch
          predicates:
            - Path=/api/book-rematch/**


eureka:
  client:
    service-url:
      defoultZone: http://lacahost:8761/eureka